; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = atmelavr
framework = arduino

We are switching to the Pico as the Controller
[env:controller]
board = uno
build_src_filter = +<controller/>,-<target/>
lib_deps =
	platformio/Streaming@0.0.0-alpha+sha.5
	Wire
monitor_speed = 115200

[env:peripheral]
board = attiny85
build_src_filter = +<target/>,-<controller/>
lib_deps = nickcengel/TinyWireSio@0.0.0-alpha+sha.722ada4382
board_build.f_cpu = 8000000L

; [env:pico]
; platform = raspberrypi
; board = pico
; ; change microcontroller
; board_build.mcu = rp2040
; framework = arduino
; monitor_speed = 115200
; upload_protocol = picotool
; upload_port = /dev/ttyACM0
